FROM aymanhab/opensim-deps:4.3.0

RUN apt-get update && apt-get --yes install \
        python3 python3-dev python3-numpy python3-scipy \
        python3-matplotlib python3-opencv \
        python3-setuptools \
        swig

RUN mkdir opensim_build && cd opensim_build && cmake ../opensim-core \
      -DBUILD_PYTHON_WRAPPING=ON \
      -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install" \
      -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF \
      && make -j8 && make -j8 install