FROM stanfordnmbl/opensim-deps:latest

MAINTAINER Ayman Habib

# Build cpp only libraries and cli for opensim-core no bindings
RUN mkdir opensim_build \
    && cd opensim_build \
    && cmake ../opensim-core \
      -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install" \
      -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF \
    && make -j8 \
    && make install \
    && rm -rf ../opensim_build \
    && cp /root/opensim_dependencies_install/adol-c/lib64/*.so* /root/opensim_install/lib 

# Set LD_LIBRARY_PATH so pyhton can load the shard libraries
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/opensim_dependencies_install/simbody/lib:/root/opensim_install/lib
ENV PATH=$PATH:/root/opensim_install/bin

# image stored at stanfordnmbl/opensim-cpp