FROM stanfordnmbl/opensim-deps:4.5

LABEL maintainer="Ayman Habib"

# Build cpp only libraries and cli for opensim-core no bindings
RUN mkdir opensim_build \
    && cd opensim_build \
    && cmake ../opensim-core \
      -DCMAKE_INSTALL_PREFIX=$OPENSIM_INSTALL -DOPENSIM_DEPENDENCIES_DIR=$OPENSIM_DEPENDENCIES_HOME \
      -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF -DBUILD_API_EXAMPLES=OFF\
    && make -j4 \
    && make install \
    && rm -rf ../opensim_build

# image stored at stanfordnmbl/opensim-cpp
